version: '3.9'

services:
  vape_store_db:
    image: postgres:14
    ports:
      - 5432:5432

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=nest2
